#!/bin/bash
# recommit_docs_v6.sh
# GroupTrack document management + cross-reference generation
# V6: Added Step 0B — field-level cross-reference export (field_crossref_raw.txt)
#     This file is uploaded to Claude at session start for full codebase context.
#
# WHAT'S NEW IN V6:
#   - Generates field_crossref_raw.txt — every file, every function, every caller,
#     every callee, lifecycle phase tags, add/change/reference status
#   - Supersedes the manual WhereUsed docx — always current from live code
#   - Combined with function_universe_raw.txt and where_used_raw.txt gives
#     Claude complete codebase awareness at session start
#
# Run from: ~/Meshtastic-Android
# Usage:    bash docs/recommit_docs_v6.sh

cd /c/Users/kixaz/Meshtastic-Android || { echo "ERROR: Not in Meshtastic-Android"; exit 1; }

DOWNLOADS="/c/Users/kixaz/Downloads"
DOCS="docs"
ARCHIVE="docs/archive"
RADIO_CONFIGS="docs/radio_configs"
CONVOY_SRC="app/src/main/java/com/geeksville/mesh/convoy"
MESH_SRC="app/src/main/java/com/geeksville/mesh"
ASSETS_SRC="app/src/main/assets"
MANIFEST="app/src/main/AndroidManifest.xml"
BUILD_GRADLE="app/build.gradle.kts"
CROSSREF="$DOCS/field_crossref_raw.txt"

echo "=== GROUPTRACK DOCS RECOMMIT v6 ==="
echo ""

mkdir -p "$DOCS"
mkdir -p "$ARCHIVE"
mkdir -p "$RADIO_CONFIGS"

# ══════════════════════════════════════════════════════════════════════════════
# Step 0A: Generate function_universe_raw.txt and where_used_raw.txt
# ══════════════════════════════════════════════════════════════════════════════
echo "--- Step 0A: Generating function universe ---"

grep -rn "fun \|object \|class \|val \|var " \
  "$CONVOY_SRC/" \
  --include="*.kt" \
  | grep -v "\/\/" \
  | grep -v "test" \
  | sed 's|app/src/main/java/com/geeksville/mesh/convoy/||' \
  > "$DOCS/function_universe_raw.txt"

FN_COUNT=$(wc -l < "$DOCS/function_universe_raw.txt")
echo "  function_universe_raw.txt: $FN_COUNT entries"

echo "--- Step 0A: Generating where-used raw data ---"

grep -rn "startRecording\|stopRecording\|finalizeTrack\|installProfileToRadio\|buildProfile\|buildSnapshot\|archiveCurrentRadio\|applyMasterConfig\|scanImportDirectory\|startDownload\|recalcLead\|startGroupTrack\|stopGroupTrack\|startTrack\|stopTrack\|pauseTrack\|resumeTrack\|onRadioPosition\|downloadTiles\|isSignedIn\|isSubscribed\|saveUser\|clearSession\|resolveLaunchRoute\|followOrganizer\|unfollowOrganizer\|createRide\|enrollRider\|compute\b\|computeStatus\|computeHeading\|assignLeadTail\|colorSegmentsByNode\|setLeadCart\|deleteTempTrack\|convoyListTracks\|loadTrackOnMap\|handleTrackFileImport\|startPhoneGps\|stopPhoneGps\|getPhoneLocation\|readLiveNodes\|tick\b\|startTick\|bindGpsService\|setLocalTiles\|setAutoPan\|setOfflineMode\|setMapTypeLabel\|setPendingDownload\|cancelDownload\|calculateTiles\|downloadTile\b\|tilePath\|registerUser\|downloadRide\|createInvite\|onGpsUpdate\|startLocationUpdates\|stopLocationUpdates\|writeGpxPoint\|migrateTiles\|getUserId\|reconnectRadio\|setGpsInterval\|removeNode" \
  "$MESH_SRC/" \
  --include="*.kt" \
  | grep -v "^.*: *\/\/" \
  | sed 's|app/src/main/java/com/geeksville/mesh/||' \
  > "$DOCS/where_used_raw.txt"

WU_COUNT=$(wc -l < "$DOCS/where_used_raw.txt")
echo "  where_used_raw.txt: $WU_COUNT call sites"

# ══════════════════════════════════════════════════════════════════════════════
# Step 0B: Generate field_crossref_raw.txt — COMPREHENSIVE CROSS-REFERENCE
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Step 0B: Generating field-level cross-reference ---"
echo "    This is the big one. Scanning every file, function, caller, callee..."
echo ""

cat > "$CROSSREF" << 'HEADER'
================================================================================
GROUPTRACK — FIELD-LEVEL CROSS-REFERENCE
================================================================================
Auto-generated by recommit_docs_v6.sh
Upload this file to Claude at session start for full codebase context.

LIFECYCLE PHASES:
  INIT    = Activity.onCreate → Hilt DI → ViewModel init{} — NO PERMISSIONS YET
  TICK    = Every 3-5s from startTick() — requires ACCESS_FINE_LOCATION guard
  MAP-LOAD = WebView.onPageFinished — permissions should be granted
  RECORD  = User taps Record → ConvoyGpsService — requires FINE_LOCATION + FOREGROUND_SERVICE
  RADIO   = Radio BLE connect/disconnect — requires BLUETOOTH_SCAN + BLUETOOTH_CONNECT
  USER    = User-initiated button/menu action — varies by action

RULES:
  INIT functions must NOT require permissions, network, or launch activities.
  TICK functions must have permission guard if accessing GPS/Location.
  Never call startActivity() during INIT or TICK.

STATUS KEY:
  [ADDED]      = New code not in stock Meshtastic
  [CHANGED]    = Modified from Meshtastic base
  [REFERENCE]  = Stock Meshtastic, referenced by convoy code
  [REMOVED]    = Was present, now removed (noted for history)

HEADER

# Add generation timestamp
echo "Generated: $(date '+%Y-%m-%d %H:%M')" >> "$CROSSREF"
echo "Branch: $(git branch --show-current)" >> "$CROSSREF"
echo "Last commit: $(git log --oneline -1)" >> "$CROSSREF"
echo "" >> "$CROSSREF"

# ── Section 1: Meshtastic Base Layer Modifications ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 1: MESHTASTIC BASE LAYER MODIFICATIONS" >> "$CROSSREF"
echo "Files OUTSIDE convoy/ that GroupTrack has changed. Every change runs at startup." >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"

# MainActivity.kt
echo "--- MainActivity.kt ---" >> "$CROSSREF"
echo "[CHANGED] Main entry point. GroupTrack modifications:" >> "$CROSSREF"
grep -n "convoy\|grouptrack\|GroupTrack\|MANAGE_EXTERNAL\|handleTrackFile\|isTrackFile\|TrackImport" \
  "$MESH_SRC/MainActivity.kt" 2>/dev/null \
  | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"

# Main.kt (ui)
echo "--- ui/Main.kt ---" >> "$CROSSREF"
echo "[CHANGED] Navigation host. GroupTrack modifications:" >> "$CROSSREF"
grep -n "convoy\|Convoy\|resolveLaunchRoute\|isSubscribed\|grouptrack\|GroupTrack" \
  "$MESH_SRC/ui/Main.kt" 2>/dev/null \
  | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"

# ConvoyNavigation.kt
echo "--- navigation/ConvoyNavigation.kt ---" >> "$CROSSREF"
echo "[ADDED] All convoy navigation routes:" >> "$CROSSREF"
grep -n "composable\|ConvoyRoutes\|resolveLaunchRoute\|isSubscribed" \
  "$MESH_SRC/navigation/ConvoyNavigation.kt" 2>/dev/null \
  | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"

# build.gradle.kts
echo "--- app/build.gradle.kts ---" >> "$CROSSREF"
echo "[CHANGED] Build config modifications:" >> "$CROSSREF"
grep -n "grouptrack\|com.grouptrack\|targetSdk\|compileSdk\|versionCode\|versionName\|signingConfig" \
  "$BUILD_GRADLE" 2>/dev/null \
  | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"

# AndroidManifest.xml
echo "--- AndroidManifest.xml ---" >> "$CROSSREF"
echo "[CHANGED] Permissions and intent filters:" >> "$CROSSREF"
grep -n "MANAGE_EXTERNAL\|WRITE_EXTERNAL\|READ_EXTERNAL\|FOREGROUND_SERVICE\|intent-filter\|convoy\|grouptrack\|application/vnd.google-earth\|gpx\|kml" \
  "$MANIFEST" 2>/dev/null \
  | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"

# ── Section 2: File Inventory with Function Counts ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 2: CONVOY FILE INVENTORY" >> "$CROSSREF"
echo "Every .kt file in convoy/ with line count and function count" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"
echo "FILE | LINES | FUNCTIONS | PURPOSE" >> "$CROSSREF"
echo "---- | ----- | --------- | -------" >> "$CROSSREF"

for f in "$CONVOY_SRC"/*.kt; do
  [ -f "$f" ] || continue
  FNAME=$(basename "$f")
  LINES=$(wc -l < "$f")
  FUNCS=$(grep -c "fun " "$f")
  # Extract first comment or class declaration for purpose
  PURPOSE=$(grep -m1 "class \|object \|\/\/ " "$f" | head -1 | sed 's|^.*//||;s|^.*class ||;s|^.*object ||' | head -c 60)
  echo "$FNAME | $LINES | $FUNCS | $PURPOSE" >> "$CROSSREF"
done
echo "" >> "$CROSSREF"

# ── Section 3: HTML Asset Files ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 3: HTML MAP ASSETS" >> "$CROSSREF"
echo "JavaScript functions in convoy map HTML files" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"

for htmlfile in "$ASSETS_SRC"/convoy_map.html "$ASSETS_SRC"/grouptrack_map.html; do
  [ -f "$htmlfile" ] || continue
  echo "--- $(basename $htmlfile) ---" >> "$CROSSREF"
  grep -n "function " "$htmlfile" | sed 's|^|  |' >> "$CROSSREF"
  echo "" >> "$CROSSREF"
done

# ── Section 4: Per-File Function Detail ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 4: PER-FILE FUNCTION DETAIL" >> "$CROSSREF"
echo "Every function in every convoy .kt file with line number" >> "$CROSSREF"
echo "For each function: who CALLS it and what it CALLS" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"

for f in "$CONVOY_SRC"/*.kt; do
  [ -f "$f" ] || continue
  FNAME=$(basename "$f")
  echo "========================================" >> "$CROSSREF"
  echo "FILE: $FNAME" >> "$CROSSREF"
  echo "========================================" >> "$CROSSREF"

  # Extract all function names with line numbers
  grep -n "fun " "$f" | while IFS= read -r line; do
    LINENUM=$(echo "$line" | cut -d: -f1)
    FUNCLINE=$(echo "$line" | cut -d: -f2-)
    # Extract function name
    FUNCNAME=$(echo "$FUNCLINE" | sed 's|.*fun \([a-zA-Z_][a-zA-Z0-9_]*\).*|\1|')

    echo "" >> "$CROSSREF"
    echo "  [$LINENUM] $FUNCLINE" >> "$CROSSREF"

    # Find callers across entire codebase (who calls this function)
    if [ ${#FUNCNAME} -gt 2 ]; then
      CALLERS=$(grep -rn "\b${FUNCNAME}\b" "$MESH_SRC/" --include="*.kt" 2>/dev/null \
        | grep -v "fun ${FUNCNAME}" \
        | grep -v "\/\/ " \
        | grep -v "$FNAME:$LINENUM:" \
        | sed "s|$MESH_SRC/||" \
        | head -15)
      if [ -n "$CALLERS" ]; then
        echo "    CALLED BY:" >> "$CROSSREF"
        echo "$CALLERS" | sed 's|^|      |' >> "$CROSSREF"
      fi
    fi
  done

  echo "" >> "$CROSSREF"
done

# ── Section 5: Lifecycle Phase Map ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 5: LIFECYCLE PHASE MAP" >> "$CROSSREF"
echo "Functions tagged by when they execute in the app lifecycle" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"

echo "--- INIT PHASE (runs during onCreate / ViewModel init) ---" >> "$CROSSREF"
grep -rn "init {\\|init{\\|override fun onCreate\\|resolveLaunchRoute\\|scanImportDirectory\\|startTick\\|admissionWindowHours\\|myNodeInfo.collect" \
  "$CONVOY_SRC/" --include="*.kt" 2>/dev/null \
  | sed "s|$CONVOY_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

echo "--- TICK PHASE (runs every 3-5 seconds) ---" >> "$CROSSREF"
grep -rn "fun tick\\|readLiveNodes\\|startPhoneGps\\|getPhoneLocation\\|stopPhoneGps\\|ConvoyEngine.compute\\|convoyLog\\|resolveMyCartId\\|_convoyState.value" \
  "$CONVOY_SRC/" --include="*.kt" 2>/dev/null \
  | sed "s|$CONVOY_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

echo "--- MAP-LOAD PHASE (runs when WebView loads) ---" >> "$CROSSREF"
grep -rn "onPageFinished\\|setTileUrl\\|setLocalTiles\\|setAutoPan\\|setOfflineMode\\|setMapTypeLabel\\|evaluateJavascript\\|loadUrl" \
  "$CONVOY_SRC/" --include="*.kt" 2>/dev/null \
  | sed "s|$CONVOY_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

echo "--- RECORD PHASE (user taps Record) ---" >> "$CROSSREF"
grep -rn "startGroupTrack\\|stopGroupTrack\\|startRecording\\|stopRecording\\|pauseRecording\\|resumeRecording\\|finalizeTrack\\|bindGpsService\\|startTrack\\|stopTrack\\|pauseTrack\\|resumeTrack\\|startLocationUpdates\\|stopLocationUpdates\\|onGpsUpdate\\|writeGpxPoint" \
  "$CONVOY_SRC/" --include="*.kt" 2>/dev/null \
  | sed "s|$CONVOY_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

echo "--- RADIO PHASE (BLE connect/config) ---" >> "$CROSSREF"
grep -rn "installProfileToRadio\\|reconnectRadio\\|buildProfile\\|buildSnapshot\\|archiveCurrentRadio\\|setGpsInterval\\|removeNode\\|meshService\\|setConfig\\|channelViewModel" \
  "$CONVOY_SRC/" --include="*.kt" 2>/dev/null \
  | sed "s|$CONVOY_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

echo "--- USER PHASE (button taps, menu actions) ---" >> "$CROSSREF"
grep -rn "setPendingDownload\\|startDownload\\|cancelDownload\\|setLeadCart\\|deleteTempTrack\\|convoyListTracks\\|loadTrackOnMap\\|handleTrackFileImport\\|saveUser\\|clearSession\\|createRide\\|enrollRider\\|followOrganizer\\|unfollowOrganizer\\|registerUser\\|downloadRide\\|createInvite" \
  "$CONVOY_SRC/" --include="*.kt" 2>/dev/null \
  | sed "s|$CONVOY_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

# ── Section 6: Known Issues from Code Comments ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 6: CODE ISSUES AND WARNINGS" >> "$CROSSREF"
echo "TODO, FIXME, BUG, HACK, WARNING, ISSUE comments in code" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"

grep -rn "TODO\|FIXME\|BUG\|HACK\|WARNING\|ISSUE\|XXX\|WORKAROUND" \
  "$CONVOY_SRC/" --include="*.kt" 2>/dev/null \
  | grep -v "import " \
  | sed "s|$CONVOY_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

grep -rn "TODO\|FIXME\|BUG\|HACK\|WARNING\|ISSUE" \
  "$ASSETS_SRC/convoy_map.html" "$ASSETS_SRC/grouptrack_map.html" 2>/dev/null \
  | sed "s|$ASSETS_SRC/||;s|^|  |" >> "$CROSSREF"
echo "" >> "$CROSSREF"

# ── Section 7: Git State ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 7: CURRENT GIT STATE" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"
echo "Branch: $(git branch --show-current)" >> "$CROSSREF"
echo "Last 5 commits:" >> "$CROSSREF"
git log --oneline -5 | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"
echo "Uncommitted changes:" >> "$CROSSREF"
git status --short | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"
echo "Stash list:" >> "$CROSSREF"
git stash list 2>/dev/null | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"

# ── Section 8: Feature Flags ──
echo "================================================================================" >> "$CROSSREF"
echo "SECTION 8: FEATURE FLAGS AND CONFIG STATE" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"
echo "" >> "$CROSSREF"
grep -n "V3_FEATURES_ENABLED\|PAYWALL_ENABLED\|SOLO_DEBUG\|TILE_SOURCES\|ACTIVE_TILE_SOURCE\|LOCAL_TILE_BASE\|TILE_DIR" \
  "$CONVOY_SRC/ConvoyConfig.kt" 2>/dev/null \
  | sed 's|^|  |' >> "$CROSSREF"
echo "" >> "$CROSSREF"

# ── Footer ──
echo "================================================================================" >> "$CROSSREF"
echo "END OF FIELD CROSS-REFERENCE" >> "$CROSSREF"
echo "Upload this file to Claude with: GroupTrack_AllDocs.txt" >> "$CROSSREF"
echo "================================================================================" >> "$CROSSREF"

XREF_LINES=$(wc -l < "$CROSSREF")
echo "  field_crossref_raw.txt: $XREF_LINES lines"
echo ""

# ══════════════════════════════════════════════════════════════════════════════
# Step 1: Copy documents from Downloads to docs/
# ══════════════════════════════════════════════════════════════════════════════
echo "--- Step 1: Copying docs from Downloads ---"

# Delete Windows duplicate copies first
find "$DOWNLOADS" -maxdepth 1 \( -name "GroupTrack*(1)*" -o -name "GroupTrack*(2)*" -o -name "GroupTrack*(3)*" \) -delete 2>/dev/null

# Copy GroupTrack documents
for ext in docx pdf txt md html; do
  for f in "$DOWNLOADS"/GroupTrack*."$ext"; do
    [ -f "$f" ] || continue
    BASENAME=$(basename "$f")
    cp "$f" "$DOCS/$BASENAME"
    echo "  Copied: $BASENAME"
  done
done

# Copy radio configs
for f in "$DOWNLOADS"/*.cfg; do
  [ -f "$f" ] || continue
  BASENAME=$(basename "$f")
  cp "$f" "$RADIO_CONFIGS/$BASENAME"
  echo "  Config: $BASENAME"
done

# Copy this script
cp "$DOWNLOADS/recommit_docs_v6.sh" "$DOCS/recommit_docs_v6.sh" 2>/dev/null

# ══════════════════════════════════════════════════════════════════════════════
# Step 2: Archive older versions
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Step 2: Archiving older versions ---"

# For versioned files (_v1, _v2, etc.), keep latest in docs/, move older to archive/
for ext in docx pdf txt md html; do
  for f in "$DOCS"/*_v[0-9]*."$ext"; do
    [ -f "$f" ] || continue
    BASENAME=$(basename "$f" ".$ext")
    # Get the base name without version suffix
    BASE=$(echo "$BASENAME" | sed 's|_v[0-9]*$||')
    # Find all versions of this file
    LATEST=$(ls -1 "$DOCS"/${BASE}_v*."$ext" 2>/dev/null | sort -V | tail -1)
    # Move all except latest to archive
    for older in "$DOCS"/${BASE}_v*."$ext"; do
      [ "$older" = "$LATEST" ] && continue
      mv "$older" "$ARCHIVE/" 2>/dev/null && echo "  Archived: $(basename $older)"
    done
  done
done

# ══════════════════════════════════════════════════════════════════════════════
# Step 3: Regenerate AllDocs.txt
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Step 3: Regenerating GroupTrack_AllDocs.txt ---"

ALLDOCS="$DOCS/GroupTrack_AllDocs.txt"
> "$ALLDOCS"

for f in "$DOCS"/*.docx; do
  [ -f "$f" ] || continue
  BASENAME=$(basename "$f")
  echo "=== $BASENAME ===" >> "$ALLDOCS"
  # Try pandoc first, fall back to python-docx
  if command -v pandoc &>/dev/null; then
    pandoc "$f" -t plain --wrap=none 2>/dev/null >> "$ALLDOCS"
  else
    python3 -c "
from docx import Document
doc = Document('$f')
for p in doc.paragraphs:
    print(p.text)
for t in doc.tables:
    for row in t.rows:
        print(' | '.join(c.text.strip() for c in row.cells))
" 2>/dev/null >> "$ALLDOCS"
  fi
  echo "" >> "$ALLDOCS"
  echo "" >> "$ALLDOCS"
done

ALLDOCS_LINES=$(wc -l < "$ALLDOCS")
echo "  GroupTrack_AllDocs.txt: $ALLDOCS_LINES lines"

# ══════════════════════════════════════════════════════════════════════════════
# Step 4: Git add and commit
# ══════════════════════════════════════════════════════════════════════════════
echo ""
echo "--- Step 4: Git commit ---"

git add "$DOCS/" --all

CHANGES=$(git diff --cached --stat | tail -1)
if [ -z "$CHANGES" ]; then
    echo "  No changes to commit."
    exit 0
fi

echo "  $CHANGES"
echo ""

DATE=$(date +"%Y-%m-%d %H:%M")
git commit -m "docs: recommit all project documents + cross-reference — $DATE"
if [ $? -ne 0 ]; then
    echo "ERROR: commit failed"
    exit 1
fi

git push origin feature/convoy-event-ride
if [ $? -ne 0 ]; then
    echo ""
    echo "WARNING: push rejected — run:"
    echo "  git push origin feature/convoy-event-ride --force-with-lease"
fi

echo ""
echo "=== DONE ==="
echo ""
echo "  Active docs:       $DOCS/"
echo "  Archived:          $ARCHIVE/"
echo "  Radio configs:     $RADIO_CONFIGS/"
echo ""
echo "  Cross-ref data (upload ALL THREE to Claude at session start):"
echo "    docs/field_crossref_raw.txt      ← NEW: comprehensive field-level reference"
echo "    docs/function_universe_raw.txt   ← all function definitions"
echo "    docs/where_used_raw.txt          ← key function call sites"
echo ""
echo "  Also upload:"
echo "    docs/GroupTrack_AllDocs.txt       ← consolidated doc text"
echo ""
